/* ===== HITMAN: WORLD OF ASSASSINATION DATA =====
   Single source of truth for the hub, per-game pages (game.html?id=),
   and character background pages (character.html?id=).
   Source-checked against hitman.fandom.com for the trilogy structure.
*/

const HM_GAMES = [
  { id: "hitman1", title: "HITMAN ™", year: "2016", cover: "hitman1.png", banner: "hitman1.png",  logo: "hitman1.png",
    tagline: "The ICA reboots its most valuable asset.",
    brief: "Agent 47 returns to active duty in a rebuilt International Contract Agency, taking on sanctioned kills that read like a world tour of the ultra-wealthy — a Paris fashion show, a Sicilian coastline, a Marrakesh embassy, a Bangkok hotel, a Colorado militia compound, and a Hokkaido hospital built for people who'd rather not be found.",
    locations: [
      { name: "Paris", desc: "A fashion show inside a lavishly restored palace, where the guest list is exactly as dangerous as the runway." },
      { name: "Sapienza", desc: "A sun-drenched Italian coastal town hiding a bioweapon lab underneath its prettiest villa." },
      { name: "Marrakesh", desc: "A crowded Moroccan embassy and marketplace, where a coup is being financed one quiet transaction at a time." },
      { name: "Bangkok", desc: "A luxury hotel housing a rock star, his entourage, and a cult with a very specific interest in his inheritance." },
      { name: "Colorado", desc: "An isolated militia compound posing as a survivalist retreat, built around secrets its own members aren't allowed to ask about." },
      { name: "Hokkaido", desc: "A private hospital for the ultra-wealthy, built into a mountainside for people who'd rather recover from surgery somewhere no one can find them." },
    ] },
  { id: "hitman2", title: "HITMAN™ 2", year: "2018", cover: "hitman2.png", banner: "hitman2.png", logo: "hitman2.png",
    tagline: "The Shadow Client's war against Providence begins in earnest.",
    brief: "47 and his handler Lucas Grey go on the offensive against Providence, the secret society that's quietly run the world from behind the ICA's own client list — tearing through a Miami race track, a cartel-run rainforest estate, a Mumbai slum-and-studio backlot, and a suburban American cul-de-sac hiding something considerably worse than nosy neighbors.",
    locations: [
      { name: "Miami", desc: "A motorsport event where the racetrack, the paddocks, and a penthouse suite are all part of the same data-harvesting operation." },
      { name: "Santa Fortuna", desc: "A Colombian rainforest estate serving as the nerve center for a cartel with far bigger clients than the drug trade alone explains." },
      { name: "Mumbai", desc: "A sprawling slum-and-film-studio backlot where a crime lord, a Bollywood set, and a hidden syndicate all share the same block." },
      { name: "Whittleton Creek", desc: "A picture-perfect Vermont cul-de-sac where the neighborhood watch has considerably more reason to be paranoid than usual." },
      { name: "Isle of Sgàil", desc: "A secretive island retreat hosting a masked ritual for the people who actually run Providence from behind the scenes." },
      { name: "New Zealand", desc: "A quiet coastal cliffside mission that doubles as the story's real beginning, long before 47 ever takes the contract." },
    ] },
  { id: "hitman3", title: "HITMAN™ III", year: "2021", cover: "hitman3.png", banner: "hitman3.png",  logo: "hitman3.png",
    tagline: "The finale of the World of Assassination trilogy.",
    brief: "The hunt for Providence's inner circle closes in for good, sending 47 from the tallest building in the world to an English murder-mystery estate, a Berlin nightclub full of fellow assassins, a Chinese tech city, an Argentine vineyard, and finally into the Carpathian Mountains for a reckoning two games in the making.",
    locations: [
      { name: "Dubai", desc: "The tallest building in the world, scaled from the inside during a heist disguised as routine corporate security." },
      { name: "Dartmoor", desc: "An English countryside estate hosting a will reading that unravels into a murder mystery 47 gets to solve by causing one." },
      { name: "Berlin", desc: "An underground nightclub crawling with fellow assassins, where blending in means looking like everyone else who's also here to kill someone." },
      { name: "Chongqing", desc: "A rain-soaked Chinese tech city where a surveillance firm's own cameras become part of the mission's biggest obstacle." },
      { name: "Mendoza", desc: "An Argentine vineyard hosting a family gathering with considerably more blood debts than wine pairings." },
      { name: "Carpathian Mountains", desc: "A remote mountain fortress housing the trilogy's final confrontation, two games and one very long grudge in the making." },
    ] },
];

const HM_ITEMS = [
  // ===== PROTAGONIST (constant across the trilogy) =====
  { id: "agent-47", category: "protagonist", name: "Agent 47", game: "all", tag: "ICA Contract Killer",
    epithet: "The World's Most Dangerous Asset",
    blurb: "A genetically engineered assassin raised from birth to be the perfect contract killer, working through the International Contract Agency and recognizable by exactly one detail he can never quite hide: the barcode tattooed on the back of his shaved head." },
  { id: "diana", category: "protagonist", name: "Diana Burnwood", game: "all", tag: "ICA Handler",
    epithet: "The Voice That Never Panics",
    blurb: "47's longtime handler, running every contract from a calm, clinical remove — until her own history with Providence turns her into far more than just the voice in his earpiece." },
  { id: "lucas-grey", category: "protagonist", name: "Lucas Grey", game: "hitman2" , tag: "Shadow Client",
    epithet: "Spec Ops Master Strategist",
    blurb: "A childhood friend of Agent 47, and is later revealed to be Subject 6, seasoned mercenary on a mission to take down Providence, an elusive power cabal with unprecedented global reach." },

  // ===== HITMAN (2016) TARGETS =====
  { id: "kalvin-rieter", category: "target", name: "Kalvin Reiter", game: "hitman1", tag: "Guided Training - The Last Yardbird",
    epithet: "The Sparrow",
    blurb: "Little is known about Kalvin Ritter's origins. Allegedly from Barbados, Ritter first emerged in London in the 1980s as a part of the notorious international jewel thief network \"The Yardbirds.\"" 
  },
  { id: "jasper-knight", category: "target", name: "Jasper Knight", game: "hitman1", tag: "Final Exam - Training Exercise",
    epithet: "Chess master, Soviet spy",
    blurb: "A world-famous chess master who murdered the Soviet ambassador to the US. The ambassador was planning to defect to the West, and Knight, a Soviet spy working under order from the KGB, ingeniously poisoned the ambassador with ricin-coated chess pieces during a private match."
  },
  { id: "novikov-margolis", category: "target", name: "Viktor Novikov & Dalia Margolis", game: "hitman1", tag: "Paris - France",
    epithet: "The ICA's First Reboot Contract",
    blurb: "Co-owners of a Parisian fashion house secretly running a private intelligence-gathering operation out of the mansion basement, eliminated during a runway show packed with exactly the kind of witnesses neither of them wanted watching." },
  { id: "caruso-santis", category: "target", name: "Silvio & Francesca De Santis Caruso", game: "hitman1", tag: "Sapienza - Italy",
    epithet: "Reclusive Bio-Chemist & Spy in Disguise",
    blurb: "A reclusive tech heir developing a genetically engineered virus in a private lab beneath his family's Italian coastal estate, unknowingly that a spy disguised as a scientist is after his research and posibbly to eliminate him" },
  { id: "zaydan-hugo", category: "target", name: "Reza Zaydan & Claus Hugo Strandberg", game: "hitman1", tag: "Marrakesh - Morocco",
    epithet: "Army General, and a White-collar Criminal",
    blurb: "After being caught swindling millions from the Moroccan people through fraud, Strandberg was scheduled to go to trial before he was broken out during a convoy hijacking. He is now hiding in the Swedish Consulate, where an angry mob has gathered demanding his arrest. Unknown to them, Strandberg's escape was orchestrated by General Zaydan, who is planning to use the civil unrest as an excuse to enforce martial law, and from there, stage a military coup to overthrow the government." },
    { id: "morgan-cross", category: "target", name: "Ken Morgan & Jordan Cross", game: "hitman1", tag: "Bangkok - Thailand",
    epithet: "Superstar Lawyer, and Murderous Rockstar",
    blurb: "A power lawyer, corporate fixer and attorney to the Cross family together with the magnetic frontman of a rock band secretly entangled in a cult built around his own late father's estate, holed up in a Bangkok hotel with the kind of entourage that makes a clean approach considerably harder." },
    { id: "freedom-fighters", category: "target", name: "Sean Rose, Maya Parvati, Penelope Graves & Ezra Berg", game: "hitman1", tag: "Colorado - USA",
    epithet: "Freedom Fighters",
    blurb: " A militia group led by environmental terrorist Sean Rose, who is believed to be the one responsible for Thomas Cross' kidnapping. Erich Soders assigns 47 to infiltrate the militia's HQ in Colorado and eliminate Rose along with three other militia members: Former Mossad interrogator Ezra Berg, former Interpol analyst Penelope Graves and former gunrunner and pirate Maya Parvati." },

    { id: "soders-yamazaki", category: "target", name: "Erich Soders & Yuki Yamazaki", game: "hitman1", tag: "Hakkaido - Japan",
    epithet: "ICA Training Director, and Providence Herald",
    blurb: "Soders, who suffers from the medical condition Situs Inversus (where his internal organs are lethally and erratically arranged), has used his connections with Providence to secure himself a right-sided heart, and a surgery at the high tech GAMA hospital in Hokkaido, Japan. Agent 47 must infiltrate the hospital and eliminate Soders. Additionally, he must eliminate Yuki Yamazaki, a Tokyo lawyer and a member of Providence's messenger corps, The Heralds, who has been sent to retrieve a list of active ICA agents from Soders." },


  // ===== HITMAN 2 (2018) TARGETS =====
    { id: "alma-reynard", category: "target", name: "Alma Reynard", game: "hitman2", tag: "Hawke's Bay - New Zealand",
    epithet: "The Mastermind",
    blurb: "a field infiltrator and intelligence officer, wanted for several counts of eco-terrorism. She is an active agent in the Shadow Client's militia. Born into a family of Basque nationalists, Reynard grew up with a solid hatred for the establishment." },
  { id: "the-knox", category: "target", name: "Robert Knox & Siera Knox", game: "hitman2", tag: "Miami - USA",
    epithet: "Pole Position, Dead Last",
    blurb: "The owner of a Miami motorsport team using the race itself as cover for a data-harvesting scheme, protected by his own daughter's rise as the team's star driver and a paddock full of people who all owe him something." },
  { id: "cali-cartel", category: "target", name: "The Delgado Cartel Leadership", game: "hitman2", tag: "Santa Fortuna — Colombia",
    epithet: "Family Business, Fatal Succession",
    blurb: "The leadership of a Colombian cartel embedded deep enough in Providence's supply lines that removing them isn't just a hit — it's a succession crisis 47 gets to trigger personally." },
  { id: "shadow-lead", category: "target", name: "The Shadow Client Eastern Leaders", game: "hitman2", tag: "Mumbai  — India",
    epithet: "The Crows of Mumbai",
    blurb: "A notorious sea pirate, Kale vanished from sight several years ago after a attempted hijacking went wrong, but has reemerged to work alongside Lucas Grey, along with two members of his old crew. 47 must travel to Mumbai to eliminate the Maelstrom and his two crew members: Vanya Shah, a crime lord ruling over the city's slums, and Dawood Rangan, a shady film producer. However, the Maelstrom's current whereabouts and appearance are unknown, meaning 47 must investigate in order to draw him out..." },
  { id: "ambrose-family", category: "target", name: "Nolan Cassidy & Janus", game: "hitman2", tag: "Whittleton Creek — Suburban Assassins",
    epithet: "The Nicest House on the Cul-de-Sac",
    blurb: "A seemingly ordinary suburban American family who turn out to be a household of professional killers hiding behind a white picket fence, block parties, and a level of neighborhood-watch paranoia that's more justified than anyone realizes." },
 { id: "ark-society", category: "target", name: "Zoe Washington & Sophia Washington (The Ark Society)", game: "hitman2", tag: "Isle of Sgàil - North Atlantic ",
    epithet: "The Treasurehunters Gathering",
    blurb: " The ancient castle island is the location of a gathering of the Ark Society, a group of ultra-wealthy elites preparing for global collapse. The Society is overseen by twin sisters Zoe and Sophia Washington, treasure hunters and Providence operatives." },
  { id: "athena-savalas", category: "target", name: "Athena Savalas", game: "hitman2", tag: "New York - USA",
    epithet: "The CEO",
    blurb: "The Director of the New York branch of the banking division of financial giant Milton-Fitzpatrick, Miss Savalas is an extremely hard-working, entirely unscrupulous woman who gave up everything personal to succeed in her life as a high-tier banker." },
  { id: "providence-members", category: "target", name: "Tyson Williams, Ljudmila Vetrova & Stephen Bradley", game: "hitman2", tag: "Haven Island - Maldives",
    epithet: "The Providence Members",
    blurb: " Three Providence Partners made transactions roughly around the same time to the same company, shortly before their supposed \"deaths\"; Haven, a reputation management service, whose secret agenda is to make wealthy criminals disappear." },


  // ===== HITMAN III (2021) TARGETS =====
  { id: "crest-akka", category: "target", name: "Noel Crest & Sinhi Venthan", game: "hitman3", tag: "Ambrose Island - Andaman Sea",
    epithet: "Shadows in the Water",
    blurb: "Crest has now traveled to Ambrose Island, an island port in the Andaman Sea, where he has teamed up with a local pirate syndicate in order to steal a control unit for an Ether Corp satellite, which he plans to use to extort Ether." },
  { id: "ingram-stuyvesant", category: "target", name: "Carl Ingram & Marcus Stuyvesant", game: "hitman3", tag: "Dubai — UAE",
    epithet: "The Opening Move",
    blurb: "The head of security for the world's tallest building, holding evidence that could expose Providence's entire network — assuming 47 can get to him before he gets to a courtroom first." },
  { id: "alexa-carlisle", category: "target", name: "Alexa Carlisle", game: "hitman3", tag: "Dartmoor — England",
    epithet: "A Murder Mystery, Except It's Real",
    blurb: "The owner of an English country estate hosting a will reading that plays out like a locked-room mystery novel, right up until the mystery guest turns out to be an actual assassin." },
  { id: "ica-agents", category: "target", name: "ICA Agents", game: "hitman3", tag: "Berlin — Germany",
    epithet: "A Night at the Outskirt Club",
    blurb: "47 must infiltrate a club, and identify and eliminate as many ICA Agents as he can, to force their handler, Jiao, to call off their attack." },
  { id: "hush-royce", category: "target", name: "Hush & Imogen Royce", game: "hitman3", tag: "Chongqing — China",
    epithet: "A Rainy Night in Chongqing",
    blurb: "Under the flickering neon lights of busy cafes and amidst a flurry of small shops and food stands crammed into tight streets, Chongqing offers travellers a respite from the demands of everyday life." },
  { id: "yates-vidal", category: "target", name: "Don Archibald Yates & Tamara Vidal", game: "hitman3", tag: "Mendoza — Argentina",
    epithet: "Farewell of a Don",
    blurb: "As one of the most well-known wine regions in South America, Mendoza is the perfect place to take in the beautiful sights and acquired tastes of Argentina. From the sloping hills to the modern vineyards, there’s plenty of opportunity to explore." },
  { id: "the-constant", category: "target", name: "The Constant (Arthur Edwards)", game: "hitman3", tag: "Carpathian Mountains — Romania",
    epithet: "Two Games of Buildup, One Mountain Fortress",
    blurb: "The shadowy founding member of Providence who has been pulling strings behind nearly every contract 47 has ever taken, finally cornered in a mountain fortress for a reckoning the whole trilogy has been building toward." },

  // ===== WEAPONS (available across all three games) =====
  { id: "fiber-wire", category: "weapon", name: "Fiber Wire", game: "all", tag: "Signature Garrote",
    epithet: "The Quietest Way to End a Contract",
    blurb: "A garrote wire concealed in a pocket or briefcase, synonymous with 47's hands-on approach to a contract whenever a firearm would be far too loud for the room." },
  { id: "silverballer", category: "weapon", name: "ICA Silverballer", game: "all", tag: "Signature Sidearm",
    epithet: "Elegant Enough for the Party, Lethal Enough to End It",
    blurb: "A pair of custom suppressed pistols issued by the ICA, polished enough to pass for evening wear and precise enough to close a contract in two rounds." },
  { id: "sieger-300", category: "weapon", name: "Sieger 300 Ghost", game: "all", tag: "Precision Sniper Rifle",
    epithet: "A Shot the Target Never Hears",
    blurb: "A long-range precision rifle built for contracts where 47 never sets foot anywhere near the room the target dies in." },
  { id: "lethal-poison", category: "weapon", name: "Lethal Poison", game: "all", tag: "Concealable Toxin",
    epithet: "Served Without a Trace",
    blurb: "A concealable toxin slipped into a target's food or drink, eliminating them without a single shot fired or a single witness realizing an assassin was ever in the building." },
  { id: "remote-explosive", category: "weapon", name: "Remote Explosive", game: "all", tag: "Detonation Device",
    epithet: "For Contracts That Call for a Bang",
    blurb: "A remote-triggered charge for the rare contract that calls for something louder, messier, and far more deniable than a clean, quiet kill." },
  { id: "concealed-blade", category: "weapon", name: "Concealed Blade", game: "all", tag: "Improvised Melee",
    epithet: "Whatever's Closest at Hand",
    blurb: "A screwdriver, a knife, or whatever else happens to be lying around a crime scene — proof that a professional never really needs a dedicated weapon to finish the job." },
];
