/* ===== ASSASSIN'S CREED ARCHIVE DATA =====
   Single source of truth, used by both index.html (roster, grouped by
   game) and character.html (per-character background page, ?id=slug).
   role: "Protagonist" | "Antagonist" | "Modern Day"
*/

const AC_GAMES = [
  { id: "ac1", title: "Assassin's Creed", year: "1191 CE", setting: "The Holy Land, Third Crusade",
    cover: "ac1.jpg", banner: "ac1.jpg",
    conflict: "In the Holy Land during the Third Crusade, Altaïr is stripped of his rank after a reckless breach of the Assassin Creed and sent to eliminate nine men manipulating the war between Crusaders and Saracens alike — only to discover his own Order's mentor has been playing a longer game than anyone realized."  },
  { id: "ezio", title: "The Ezio Trilogy", year: "1476 – 1512 CE", setting: "Renaissance Italy & Constantinople",
    cover: "ezio.jpg", banner: "ezio.jpg",
    conflict: "Across three decades, Ezio Auditore rebuilds a shattered Assassin Brotherhood from the ashes of his family's execution, dismantling a Templar conspiracy that reaches from the streets of Florence into the Vatican itself, and finally into the vault beneath Masyaf where Altaïr's own legacy waits."  },
  { id: "ac3", title: "Assassin's Creed III", year: "1770s CE", setting: "Colonial America",
    cover: "ac3.jpg", banner: "ac3.jpg",
    conflict: "As the American Revolution ignites, Ratonhnhaké:ton fights to protect his Mohawk homeland from both a Templar conspiracy led by his own father and the war itself, which threatens to consume the land no matter which side wins it."  },
  { id: "ac4", title: "Assassin's Creed IV: Black Flag", year: "1715 – 1722 CE", setting: "The Caribbean",
    cover: "ac4.jpg", banner: "ac4.jpg",
    conflict: "A Welsh privateer stumbles into a centuries-old war after impersonating a dead Assassin, and is drawn deeper into a hunt for the Observatory — a precursor site both Assassins and Templars would tear the Caribbean apart to control."  },
  { id: "rogue", title: "Assassin's Creed Rogue", year: "1750s CE", setting: "North America & the North Atlantic",
    cover: "rogue.jpg", banner: "rogue.jpg",
    conflict: "After surviving a mission that kills nearly everyone he knows, Shay Cormac breaks from the Assassin Brotherhood over its reckless pursuit of precursor artifacts, and joins the Templars to hunt down the very Order that raised him."  },
  { id: "unity", title: "Assassin's Creed Unity", year: "1789 – 1794 CE", setting: "Paris, French Revolution",
    cover: "unity.jpg", banner: "unity.jpg",
    conflict: "Adopted into a Templar household as a boy, Arno Dorian is framed for his foster father's murder and inducted into the Assassin Brotherhood, chasing the truth through a French Revolution that neither Assassins nor Templars can fully control."  },
  { id: "syndicate", title: "Assassin's Creed Syndicate", year: "1868 CE", setting: "Victorian London",
    cover: "syndicate.jpg", banner: "syndicate.jpg",
    conflict: "Twin Assassins Jacob and Evie Frye arrive in Victorian London to find the city's underworld and its industry both quietly owned by a single Templar-run syndicate, and set out to break its grip street by street."  },
  { id: "origins", title: "Assassin's Creed Origins", year: "49 – 43 BCE", setting: "Ptolemaic Egypt",
    cover: "origins.jpg", banner: "origins.jpg",
    conflict: "A Medjay's hunt for the masked cult responsible for his son's death uncovers a secret order manipulating Ptolemaic Egypt from the shadows — and becomes the first spark of the Brotherhood that will one day be called the Hidden Ones."  },
  { id: "odyssey", title: "Assassin's Creed Odyssey", year: "431 – 422 BCE", setting: "Ancient Greece, Peloponnesian War",
    cover: "odyssey.jpg", banner: "odyssey.jpg",
    conflict: "A Spartan mercenary exiled as a child is drawn into a war against a cult secretly steering the Peloponnesian War from behind the scenes, all while hunting the family a false prophecy tore apart."  },
  { id: "valhalla", title: "Assassin's Creed Valhalla", year: "873 CE", setting: "Viking-Age England",
    cover: "valhalla.jpg", banner: "valhalla.jpg",
    conflict: "A Norse raider leads their clan to a new home in England only to find a Templar-precursor order already entrenched in its politics, turning a search for land into a war fought in the shadows of Saxon courts."  },
  { id: "mirage", title: "Assassin's Creed Mirage", year: "861 CE", setting: "Baghdad, Abbasid Caliphate",
    cover: "mirage.jpg", banner: "mirage.jpg",
    conflict: "A street thief turned Hidden One is sent to Baghdad to dismantle a secretive Order operating within the Caliphate's own court, only to find that the vengeance driving him may be exactly what that Order is counting on."  },
  { id: "shadows", title: "Assassin's Creed Shadows", year: "1579 CE", setting: "Sengoku-era Japan",
    cover: "shadows.jpg", banner: "shadows.jpg",
    conflict: "As Oda Nobunaga's campaign to unify Japan tears through the country, a shinobi orphaned by his war and the African samurai who served under him are drawn together against a hidden order manipulating the conflict from within."  },
];

const AC_CHARACTERS = [
  // ===== ASSASSIN'S CREED (2007) =====
  { id: "altair", name: "Altaïr Ibn-La'Ahad", game: "ac1", role: "Protagonist",
    affiliation: "Assassin Brotherhood", era: "1191 CE, The Holy Land",
    epithet: "Pride Before the Fall",
    blurb: "A master Assassin stripped of his rank after a reckless failure, forced to earn his place back one target at a time — only to discover his own Order has been compromised from within." },
  { id: "almualim", name: "Al Mualim", game: "ac1", role: "Antagonist",
    affiliation: "Assassin Brotherhood (secretly corrupted)", era: "1191 CE, Masyaf",
    epithet: "The Teacher's Lie",
    blurb: "The Assassin Order's own Mentor, revealed to be chasing the same artifact he trained his students to protect the world from, using their loyalty as the instrument of his ambition." },

  // ===== THE EZIO TRILOGY =====
  { id: "ezio", name: "Ezio Auditore da Firenze", game: "ezio", role: "Protagonist",
    affiliation: "Assassin Brotherhood", era: "1476 – 1512 CE, Italy & Constantinople",
    epithet: "A Life, Fully Lived",
    blurb: "A young Florentine noble turned lifelong Assassin after his family is executed on false charges, spending the next three decades dismantling the conspiracy responsible, city by city." },
  { id: "rodrigo", name: "Rodrigo Borgia", game: "ezio", role: "Antagonist",
    affiliation: "Templar Order", era: "1492 – 1503 CE, Rome",
    epithet: "The Spaniard Pope",
    blurb: "A Templar Grand Master who buys his way into the papacy itself, treating the Church as just another lever to pull in the hunt for a relic that could make him unstoppable." },
  { id: "cesare", name: "Cesare Borgia", game: "ezio", role: "Antagonist",
    affiliation: "Templar Order", era: "1492 – 1507 CE, Rome",
    epithet: "The Spaniard Valencian",
    blurb: "An Italian condottiero and nobleman, the illegitimate son of Rodrigo Borgia, and a nemesis of the Assassin Ezio Auditore da Firenze. Like his father, he was also a member of the Roman Rite of the Templar Order, serving as its de facto leader from 1500 to 1503 before assuming the title of Grand Master upon Rodrigo's death." },
  { id: "ahmet", name: "Prince Ahmet bin Bayezid", game: "ezio", role: "Antagonist",
    affiliation: "Templar Order", era: "1492 – 1503 CE, Rome",
    epithet: "Master of the Byzantine Rite",
    blurb: "Tired of the feuds that divided men, Ahmet joined the Templar Order, eventually becoming the Grand Master of the Byzantine Rite." },

  // ===== ASSASSIN'S CREED III =====
  { id: "connor", name: "Ratonhnhaké:ton \"Connor\"", game: "ac3", role: "Protagonist",
    affiliation: "Assassin Brotherhood", era: "1770s CE, Colonial America",
    epithet: "Two Worlds, One Fight",
    blurb: "A Mohawk-Kanien'kehá:ka assassin fighting to protect his homeland from both empires closing in on it, only to find the man orchestrating the worst of it is his own father." },
  { id: "haytham", name: "Haytham Kenway", game: "ac3", role: "Antagonist",
    affiliation: "Templar Order", era: "1750s – 1780s CE, Colonial America",
    epithet: "Order, His Way",
    blurb: "A Templar Grand Master who genuinely believes control is kinder than freedom, and who never quite manages to make that argument land with the son on the other end of his blade." },
    { id: "lee", name: "Charles Henry Lee", game: "ac3", role: "Antagonist",
    affiliation: "Templar Order", era: "1750s – 1780s CE, Colonial America",
    epithet: "The Grand Master",
    blurb: "A British soldier and veteran of the Seven Years' War, as well as a member of the Templar Order. Following Haytham's death in 1781, Lee briefly became the Grand Master of the Colonial Templars, until his death in 1782 at the hands of Haytham's son, the Assassin Ratonhnhaké:ton." },

  // ===== ASSASSIN'S CREED IV: BLACK FLAG =====
  { id: "edward", name: "Edward Kenway", game: "ac4", role: "Protagonist",
    affiliation: "Privateer, later Assassin-aligned", era: "1715 – 1722 CE, The Caribbean",
    epithet: "Gold Before the Creed",
    blurb: "A Welsh privateer chasing riches and a stolen identity through the Golden Age of Piracy, who backs into a war between Assassins and Templars long before he decides which side he's actually on." },
  { id: "woodesrogers", name: "Woodes Rogers", game: "ac4", role: "Antagonist",
    affiliation: "Templar-backed Royal Navy", era: "1718 – 1722 CE, Nassau",
    epithet: "The Pirates' Reckoning",
    blurb: "A privateer-turned-governor tasked with stamping out piracy in the Bahamas for good, treating Nassau's entire pirate republic as a problem with only one acceptable ending." },

  // ===== ASSASSIN'S CREED ROGUE =====
  { id: "shay", name: "Shay Patrick Cormac", game: "rogue", role: "Protagonist",
    affiliation: "Assassin, later Templar Order", era: "1750s CE, North America & North Atlantic",
    epithet: "The Brotherhood He Left",
    blurb: "A promising young Assassin who breaks from the Brotherhood after a mission goes catastrophically wrong, and spends the rest of his life hunting the mentors who sent him on it." },
  { id: "achilles", name: "Achilles Davenport", game: "rogue", role: "Antagonist",
    affiliation: "Assassin Brotherhood", era: "1750s CE, New York Colony",
    epithet: "A Mentor, Marked",
    blurb: "Shay's own former mentor and Brotherhood leader, who refuses to see the danger in what he's protecting until his one-time student is standing in front of him as an enemy." },
    { id: "liam", name: "Liam O'Brien", game: "rogue", role: "Antagonist",
    affiliation: "Assassin Brotherhood", era: "1750s CE, New York Colony",
    epithet: "A Friend, Marked",
    blurb: "Liam was responsible for supervising Shay and, despite being a few years his elder and more experienced, the two formed a brotherly bond." },

  // ===== ASSASSIN'S CREED UNITY =====
  { id: "arno", name: "Arno Dorian", game: "unity", role: "Protagonist",
    affiliation: "Assassin Brotherhood", era: "1789 – 1794 CE, Paris",
    epithet: "Guilty by Association",
    blurb: "A young nobleman's adopted son framed for his guardian's murder, whose search for the truth pulls him into the Brotherhood just as France tears itself apart around him." },
  { id: "germain", name: "François-Thomas Germain", game: "unity", role: "Antagonist",
    affiliation: "Templar Order", era: "1789 – 1794 CE, Paris",
    epithet: "Liberty's Puppeteer",
    blurb: "A Templar Grand Master who helps engineer the Revolution's chaos from the shadows, convinced that a France broken all the way down is the only France he can rebuild in his own image." },

  // ===== ASSASSIN'S CREED SYNDICATE =====
  { id: "jacob", name: "Jacob Frye", game: "syndicate", role: "Protagonist",
    affiliation: "Assassin Brotherhood", era: "1868 CE, London",
    epithet: "London's New Gang Lord",
    blurb: "A brash young Assassin who builds an entire street gang from scratch just to have enough muscle to take on London's Templar-run underworld directly." },
  { id: "evie", name: "Evie Frye", game: "syndicate", role: "Protagonist",
    affiliation: "Assassin Brotherhood", era: "1868 CE, London",
    epithet: "The Patient Twin",
    blurb: "Jacob's twin sister and the more disciplined half of the pair, chasing a lost Piece of Eden through London while quietly cleaning up the messes her brother's approach tends to leave behind." },
     { id: "thorne", name: "Lucy Thorne", game: "syndicate", role: "Antagonist",
    affiliation: "Templar Order", era: "1868 CE, London",
    epithet: "The Reseacher",
    blurb: "A Templar in her quest to find the Shroud of Eden, she frequently came into conflict with the Assassin Evie Frye, who also hoped to acquire the artifact and keep it out of Templar hands." },
  { id: "crawford", name: "Crawford Starrick", game: "syndicate", role: "Antagonist",
    affiliation: "Templar Order", era: "1868 CE, London",
    epithet: "The City in His Pocket",
    blurb: "A Templar Grand Master who has quietly bought up half of industrial London — its factories, its politicians, its police — long before the Frye twins ever set foot in the city." },
   

  // ===== ASSASSIN'S CREED ORIGINS =====
  { id: "bayek", name: "Bayek of Siwa", game: "origins", role: "Protagonist",
    affiliation: "Founder, the Hidden Ones", era: "49 – 43 BCE, Ptolemaic Egypt",
    epithet: "The Last Medjay",
    blurb: "The last of Egypt's ancient Medjay protectors, hunting down the secret order responsible for his son's death — and, without fully intending to, laying the first stones of the Assassin Brotherhood along the way." },
  { id: "aya", name: "Aya of Alexandria", game: "origins", role: "Protagonist",
    affiliation: "Founder, the Hidden Ones", era: "49 – 43 BCE, Ptolemaic Egypt",
    epithet: "Amunet Rising",
    blurb: "Bayek's wife and equal partner in grief and purpose, whose own campaign against the Order eventually takes her to Rome and toward the identity history remembers as Amunet." },
  { id: "flavius", name: "Flavius Metellus", game: "origins", role: "Antagonist",
    affiliation: "Order of the Ancients", era: "49 – 47 BCE, Egypt & Cyrenaica",
    epithet: "The Lion's Cruelty",
    blurb: "A Roman proconsul and secret leader of the Order's founding circle, whose casual cruelty toward one Medjay's family sets the entire chain of vengeance that built the Hidden Ones into motion." },

  // ===== ASSASSIN'S CREED ODYSSEY =====
  { id: "kassandra", name: "Kassandra", game: "odyssey", role: "Protagonist",
    affiliation: "Misthios (mercenary), Isu bloodline", era: "431 – 422 BCE, Ancient Greece",
    epithet: "The Eagle Bearer",
    blurb: "A mercenary of rare and ancient bloodline, dragged out of exile and into the middle of the Peloponnesian War by a cult that seems to know a great deal more about her family than she does." },
  { id: "deimos", name: "Deimos", game: "odyssey", role: "Antagonist",
    affiliation: "The Cult of Kosmos", era: "422 BCE, Greece",
    epithet: "The Brother Reforged",
    blurb: "Kassandra's own brother, separated from her in childhood and raised by a secret cult into a weapon they call the Wolf of Sparta, with no memory left of who he was before them." },

  // ===== ASSASSIN'S CREED VALHALLA =====
  { id: "eivor", name: "Eivor Varinsdottir", game: "valhalla", role: "Protagonist",
    affiliation: "Raven Clan, later Hidden Ones ally", era: "873 CE, England",
    epithet: "Wolf-Kissed",
    blurb: "A Norse raider leading her clan to a new home in England, whose search for land and settlement keeps circling back to a secretive order with plans for the whole island." },
  { id: "aelfred", name: "King Aelfred of Wessex", game: "valhalla", role: "Antagonist",
    affiliation: "Order of the Ancients, sympathizer", era: "871 – 899 CE, Wessex",
    epithet: "Unity at Any Cost",
    blurb: "A king determined to unify England under one crown and one faith, willing to let the Order's influence guide his hand as long as it moves him closer to that single goal." },

  // ===== ASSASSIN'S CREED MIRAGE =====
  { id: "basim", name: "Basim Ibn Ishaq", game: "mirage", role: "Protagonist",
    affiliation: "Hidden Ones", era: "861 CE, Baghdad",
    epithet: "A Thief's Ascension",
    blurb: "A street thief in Abbasid Baghdad recruited into the Hidden Ones, whose rise through the Brotherhood's ranks is shadowed the whole way by visions he can't yet explain." },
  { id: "roshan", name: "Roshan", game: "mirage", role: "Antagonist",
    affiliation: "Hidden Ones", era: "861 CE, Baghdad & Alamut",
    epithet: "A Mentor's Last Secret",
    blurb: "Basim's own mentor in the Hidden Ones, who has kept the truth of his identity hidden for his own protection — right up until the moment that secret is the only thing left standing between them." },

  // ===== ASSASSIN'S CREED SHADOWS =====
  { id: "naoe", name: "Fujibayashi Naoe", game: "shadows", role: "Protagonist",
    affiliation: "Iga Shinobi, Assassin Brotherhood", era: "1579 CE, Iga Province, Japan",
    epithet: "The Shinobi's Vengeance",
    blurb: "The daughter of one of Iga's most respected shinobi, trained to be his equal and forced to use every bit of it when her home and her father are torn from her in a single night." },
  { id: "yasuke", name: "Yasuke", game: "shadows", role: "Protagonist",
    affiliation: "Retainer to Oda Nobunaga", era: "1579 CE, Azuchi-Momoyama Japan",
    epithet: "The Outsider Samurai",
    blurb: "A real historical African samurai in service to warlord Oda Nobunaga, whose outsider's perspective on Japan's civil wars puts him on an unlikely path alongside a shinobi with her own war to fight." },
    { id: "nuno", name: "Nuno Caro", game: "shadows", role: "Antagonist",
    affiliation: "Portugese Rite, Japanese Rite", era: "1574- 1582 CE,  Japan",
    epithet: "Merchant",
    blurb: " A Portuguese merchant, slaver, and member of the Portuguese Rite of the Templar Order during the 16th century. Commissioned by the Inner Sanctum, Caro exploited the resources and trade of Japan with the intent of subjugating its people under Templar rule" },
    { id: "wada", name: "Wada Koretake", game: "shadows", role: "Antagonist",
    affiliation: "Oda Clan, Shinbakufu", era: "1574- 1582 CE,  Japan",
    epithet: "One-Eared Demon",
    blurb: "Also known as The Wounded, was a samurai who served as a retainer to the daimyō Oda Nobunaga during the late 16th century." },
  // ===== MODERN DAY =====
  { id: "desmond", name: "Desmond Miles", game: "modern", role: "Modern Day",
    affiliation: "Assassin Brotherhood (modern)", era: "2012 CE, present day",
    epithet: "Born Into the War",
    blurb: "A bartender who spent his whole life running from his Assassin family's legacy, only to be pulled back in and asked to relive his ancestors' memories to stop a global catastrophe he didn't choose." },
  { id: "layla", name: "Layla Hassan", game: "modern", role: "Modern Day",
    affiliation: "Abstergo, later Assassin Brotherhood (modern)", era: "2018 – 2020 CE, present day",
    epithet: "The Reluctant Successor",
    blurb: "An Abstergo researcher who defects after uncovering more than her employer ever meant for her to see, inheriting a role in the ancient war she spent her career studying from the outside." },
];
